// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvqUzCYItgV1Mlu5ss-Aijp0o7fZoUlBE',
    appId: '1:175846833247:web:3d95cb1821e99092702fea',
    messagingSenderId: '175846833247',
    projectId: 'undercover-game-app',
    authDomain: 'undercover-game-app.firebaseapp.com',
    storageBucket: 'undercover-game-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcReQrCL6UY_bcI-BsIglvleL0wnJVEBU',
    appId: '1:175846833247:android:a193d236e1e03d12702fea',
    messagingSenderId: '175846833247',
    projectId: 'undercover-game-app',
    storageBucket: 'undercover-game-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHH-fuZg7iYJSj_SPaK1vO2sWNxUnqUvM',
    appId: '1:175846833247:ios:4b48609ae6409241702fea',
    messagingSenderId: '175846833247',
    projectId: 'undercover-game-app',
    storageBucket: 'undercover-game-app.firebasestorage.app',
    iosBundleId: 'com.example.undercoverGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHH-fuZg7iYJSj_SPaK1vO2sWNxUnqUvM',
    appId: '1:175846833247:ios:4b48609ae6409241702fea',
    messagingSenderId: '175846833247',
    projectId: 'undercover-game-app',
    storageBucket: 'undercover-game-app.firebasestorage.app',
    iosBundleId: 'com.example.undercoverGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvqUzCYItgV1Mlu5ss-Aijp0o7fZoUlBE',
    appId: '1:175846833247:web:6891634966573109702fea',
    messagingSenderId: '175846833247',
    projectId: 'undercover-game-app',
    authDomain: 'undercover-game-app.firebaseapp.com',
    storageBucket: 'undercover-game-app.firebasestorage.app',
  );
}
